[".local/share/antidote"]
  type = "git-repo"
  url = "https://github.com/mattmc3/antidote.git"
  refreshPeriod = "168h"
[".local/share/tmux"]
  type = "git-repo"
  url = "https://github.com/gpakosz/.tmux.git"
  refreshPeriod = "168h"
[".local/share/vivalarc"]
  type = "git-repo"
  url = "https://github.com/tovifun/VivalArc.git"
  refreshPeriod = "168h"
