[".local/share/zsh/fzf-tab"]
  type = "git-repo"
  url = "https://github.com/Aloxaf/fzf-tab.git"
  refreshPeriod = "168h"
[".local/share/tmux"]
  type = "git-repo"
  url = "https://github.com/gpakosz/.tmux.git"
  refreshPeriod = "168h"
