[".local/share/antidote"]
  type = "git-repo"
  url = "https://github.com/mattmc3/antidote.git"
  refreshPeriod = "168h"
[".local/share/tmux"]
  type = "git-repo"
  url = "https://github.com/gpakosz/.tmux.git"
  refreshPeriod = "168h"
[".config/delta/catppuccin.gitconfig"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/delta/main/catppuccin.gitconfig"
  refreshPeriod = "168h"
[".config/bat/themes/Catppuccin Latte.tmTheme"]
  type = "file"
  url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Latte.tmTheme"
  refreshPeriod = "168h"
[".config/bat/themes/Catppuccin Mocha.tmTheme"]
  type = "file"
  url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme"
  refreshPeriod = "168h"
[".config/k9s/skins/catppuccin-latte.yaml"]
  type = "file"
  url = "https://github.com/catppuccin/k9s/raw/main/dist/catppuccin-latte.yaml"
  refreshPeriod = "168h"
[".config/k9s/skins/catppuccin-mocha.yaml"]
  type = "file"
  url = "https://github.com/catppuccin/k9s/raw/main/dist/catppuccin-mocha.yaml"
  refreshPeriod = "168h"
