name: Assistant
version: 0.0.1
schema: v1

models:
  - name: Claude Sonnet 4
    provider: openai
    model: anthropic/claude-sonnet-4
    apiKey: ${{ secrets.REMOTE_API_KEY }}
    apiBase: ${{ secrets.REMOTE_API_BASE }}
    defaultCompletionOptions:
      contextLength: 200000
    cacheBehavior:
      cacheSystemMessage: true
      cacheConversation: true
    capabilities:
      - tool_use
      - image_input
    roles:
      - chat
      - edit
      - apply
    requestOptions:
      extraBodyProperties:
        reasoning_effort: high
  - name: Autocomplete
    provider: openai
    model: qwen2.5-coder:3b-base-q4_K_M
    apiBase: ${{ secrets.LOCAL_API_BASE }}
    defaultCompletionOptions:
      contextLength: 8000
    roles:
      - autocomplete
  - name: Embedding
    provider: openai
    model: bge-m3:latest
    apiBase: ${{ secrets.LOCAL_API_BASE }}
    embedOptions:
      maxChunkSize: 500
    roles:
      - embed
  - name: Rerank
    provider: cohere
    model: cohere/rerank-v3.5
    apiKey: ${{ secrets.REMOTE_API_KEY }}
    apiBase: ${{ secrets.REMOTE_API_BASE }}
    roles:
      - rerank
context:
  - provider: file
  - provider: code
  - provider: folder
  - provider: diff
  - provider: url
  - provider: codebase
    params:
      nRetrieve: 1000
      nFinal: 10
      useReranking: true
rules:
  - >-
    - Do not give unnecessary explanations and get straight to the point

    - Assume that I have all the required technical knowledge to understand the
    code and only bring relevant knowledge only to correct any misunderstandings
    I have

    - Always answer in a concise and easy to understand format
